### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by perploug**
Updates package dependencies to their latest versions to patch security issues. 

- [x] Updated dependencies and devdependencies in package.json
- [x] Updated the test coverage to nyc from instanbul
- [x] Tests are passing

### CODE REVIEW

**Comment by tallbrick** [comment]
@perploug it looks like you'll need to update the Travis CI config files to be compatible with your changes (note the above build errors).  `const` and `let` weren't supported until at least Node v6.0.0.

You should consider updating this property in the .travis.yml:
```
node_js:
- '8.0.0'
- '7.0.0'
- '6.0.0'
- iojs
```

Of course you could also use more recent node versions as well...
https://node.green/

**Comment by tallbrick** [comment]
@marcellodesales 

This PR resolves some nasty vulerabilities (which puts the ongoing use of this lib in question).  Any chance you could review this one?

**Comment by marcellodesales** [comment]
@tallbrick I will get to it during `hacktoberfest`!

**Comment by marcellodesales** [comment]
@tallbrick @perploug any interest in updating the travis build with the recent versions of node? I can merge this PR soon after the build passes...

**Comment by marcellodesales** [comment]
Done on #16

**Pull request closed without merging**
